version: "3.8"

services:
  # Development service
  app-dev:
    build:
      context: .
      target: development
    container_name: hoteleria-backend-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    networks:
      - app-network

  # Production service
  app-prod:
    build:
      context: .
      target: production
    container_name: hoteleria-backend-prod
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
